#!/bin/sh

# get current user and his home directory
USER=$(whoami)
HOME=$(eval echo "~${USER}")

# create Viber home directory
VIBER_HOME="${HOME}/.viberhome"
mkdir -p ${VIBER_HOME}

# setup permissons
#export SANDBOX_DENY="${HOME}"
export SANDBOX_WRITE="/dev/snd:/dev/dri:${VIBER_HOME}"

export SANDBOX_READ="${SANDBOX_READ}:/etc"
export SANDBOX_READ="${SANDBOX_READ}:/dev"
export SANDBOX_READ="${SANDBOX_READ}:/proc"
export SANDBOX_READ="${SANDBOX_READ}:/run"
export SANDBOX_READ="${SANDBOX_READ}:/bin"
export SANDBOX_READ="${SANDBOX_READ}:/usr"
export SANDBOX_READ="${SANDBOX_READ}:/lib"
export SANDBOX_READ="${SANDBOX_READ}:/opt"
export SANDBOX_READ="${SANDBOX_READ}:/var"
export SANDBOX_READ="${SANDBOX_READ}:/sys"
export SANDBOX_READ="${SANDBOX_READ}:${VIBER_HOME}"

# setup Viber environment
export LD_LIBRARY_PATH=/opt/viber
export HOME=${VIBER_HOME}
cd ${HOME}

sandbox /opt/viber/Viber ${@}
